author: 若离QQ：2909998156
# 推送方式：0：邮件推送；1：qmsg推送；2：pushplus推送
sendType: 1
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''
# submitForm提交数据进行加密的api接口
encryptApi: 'https://api.ruoli.cc/wise/getEncryption'


#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  - user:
        # 任务类型（收集：0、签到：1、查寝：2）
        type: 1
        #username 学号或者工号
        username: '202005002179'
        #password 密码
        password: 'yjhrying520'
        #address 地址，定位信息
        address: '中国云南省昆明市五华区鸿运街道金色大道辅路'
        #sendKey 当sendType25为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
        sendKey: '2547855072'
        #school 学校全称
        schoolName: 云南财经大学
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        #lon 经度
        lon: 102.727674
        #lat 纬度
        lat: 25.094809
        #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
        abnormalReason: ''
      
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 表单信息
        forms:
          - form:
              title: 你现在的体温是？
              value: 正常，37.3℃以下
  - user:
        # 任务类型（收集：0、签到：1、查寝：2）
        type: 1
        #username 学号或者工号
        username: '201805002669'
        #password 密码
        password: '256265'
        #address 地址，定位信息
        address: '中国云南省昆明市五华区鸿运街道金色大道辅路'
        #sendKey 当sendType25为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
        sendKey: '2547855072'
        #school 学校全称
        schoolName: 云南财经大学
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        #lon 经度
        lon: 102.727674
        #lat 纬度
        lat: 25.094809
        #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
        abnormalReason: ''
      
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 表单信息
        forms:
          - form:
              title: 你现在的体温是？
              value: 正常，37.3℃以下
  - user:
        # 任务类型（收集：0、签到：1、查寝：2）
        type: 1
        #username 学号或者工号
        username: '202005002180'
        #password 密码
        password: 'Szp19991949'
        #address 地址，定位信息
        address: '中国云南省昆明市五华区鸿运街道金色大道辅路'
        #sendKey 当sendType25为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
        sendKey: '2547855072'
        #school 学校全称
        schoolName: 云南财经大学
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        #lon 经度
        lon: 102.727674
        #lat 纬度
        lat: 25.094809
        #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
        abnormalReason: ''
      
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 表单信息
        forms:
          - form:
              title: 你现在的体温是？
              value: 正常，37.3℃以下   
  - user:
        # 任务类型（收集：0、签到：1、查寝：2）
        type: 1
        #username 学号或者工号
        username: '202005002178'
        #password 密码
        password: 'pxq7tp2c'
        #address 地址，定位信息
        address: '中国云南省昆明市五华区鸿运街道金色大道辅路'
        #sendKey 当sendType25为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
        sendKey: '2547855072'
        #school 学校全称
        schoolName: 云南财经大学
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        #lon 经度
        lon: 102.727674
        #lat 纬度
        lat: 25.094809
        #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
        abnormalReason: ''
      
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 表单信息
        forms:
          - form:
              title: 你现在的体温是？
              value: 正常，37.3℃以下      
  - user:
        # 任务类型（收集：0、签到：1、查寝：2）
        type: 1
        #username 学号或者工号
        username: '202005002177'
        #password 密码
        password: 'fxw123456'
        #address 地址，定位信息
        address: '中国云南省昆明市五华区鸿运街道金色大道辅路'
        #sendKey 当sendType25为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
        sendKey: '2547855072'
        #school 学校全称
        schoolName: 云南财经大学
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        #lon 经度
        lon: 102.727674
        #lat 纬度
        lat: 25.094809
        #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
        abnormalReason: ''
      
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 表单信息
        forms:
          - form:
              title: 你现在的体温是？
              value: 正常，37.3℃以下   
  - user:
        # 任务类型（收集：0、签到：1、查寝：2）
        type: 1
        #username 学号或者工号
        username: '202105004640'
        #password 密码
        password: '880620'
        #address 地址，定位信息
        address: '中国云南省昆明市五华区鸿运街道金色大道辅路'
        #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
        sendKey: '2547855072'
        #school 学校全称
        schoolName: 云南财经大学
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        #lon 经度
        lon: 102.727674
        #lat 纬度
        lat: 25.094809
        #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
        abnormalReason: ''
      
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 表单信息
        forms:
          - form:
              title: 你现在的体温是？
              value: 正常，37.3℃以下
  - user:
        # 任务类型（收集：0、签到：1、查寝：2）
        type: 1
        #username 学号或者工号
        username: '202005003211'
        #password 密码
        password: 'abd23579'
        #address 地址，定位信息
        address: '中国云南省昆明市五华区鸿运街道金色大道辅路'
        #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
        sendKey: '2547855072'
        #school 学校全称
        schoolName: 云南财经大学
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        #lon 经度
        lon: 102.727674
        #lat 纬度
        lat: 25.094809
        #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
        abnormalReason: ''
      
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 表单信息
        forms:
          - form:
              title: 你现在的体温是？
              value: 正常，37.3℃以下
  - user:
        # 任务类型（收集：0、签到：1、查寝：2）
        type: 1
        #username 学号或者工号
        username: '202105004641'
        #password 密码
        password: '111528'
        #address 地址，定位信息
        address: '中国云南省昆明市五华区鸿运街道金色大道辅路'
        #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
        sendKey: '2547855072'
        #school 学校全称
        schoolName: 云南财经大学
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        #lon 经度
        lon: 102.727674
        #lat 纬度
        lat: 25.094809
        #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
        abnormalReason: ''
      
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 表单信息
        forms:
          - form:
              title: 你现在的体温是？
              value: 正常，37.3℃以下
  - user:
        # 任务类型（收集：0、签到：1、查寝：2）
        type: 1
        #username 学号或者工号
        username: '201905001175'
        #password 密码
        password: '2020223'
        #address 地址，定位信息
        address: '中国云南省昆明市五华区鸿运街道金色大道辅路'
        #sendKey 当sendType25为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
        sendKey: '2547855072'
        #school 学校全称
        schoolName: 云南财经大学
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        #lon 经度
        lon: 102.727674
        #lat 纬度
        lat: 25.094809
        #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
        abnormalReason: ''
      
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 表单信息
        forms:
          - form:
              title: 你现在的体温是？
              value: 正常，37.3℃以下
 
